name = "mymahir-project"
compatibility_date = "2024-05-01"

main = "express/server.js"

[assets]
directory = "angularside/dist/angularside/browser"
binding = "ASSETS"

[[d1_databases]]
binding = "DB" # We rename the binding to "DB" so your code can simply call env.DB.prepare()
database_name = "my-capstone-db"
database_id = "a1d64862-56d4-461f-a441-4b1fe7d254cd"