# Stage 1: Build the Angular app
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration=production

# Stage 2: Serve using Nginx web server
FROM nginx:alpine
COPY --from=build /app/dist/angularSide/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Expose port 80 for user traffic
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

