-- 1. THE USERS TABLE
CREATE TABLE IF NOT EXISTS users (
  userId INT AUTO_INCREMENT PRIMARY KEY,
  userName VARCHAR(255) NOT NULL,
  userEmail VARCHAR(255) NOT NULL UNIQUE,
  userPassword VARCHAR(255) NOT NULL,
  userStatus VARCHAR(50) DEFAULT 'active',
  quizCompleted INT DEFAULT 0,
  userRole VARCHAR(50) DEFAULT 'student'
) ENGINE=InnoDB;

-- 2. THE COURSES TABLE
CREATE TABLE IF NOT EXISTS courses (
  courseId INT AUTO_INCREMENT PRIMARY KEY,
  courseName VARCHAR(255) NOT NULL,
  courseStatus VARCHAR(50) DEFAULT 'Draft',
  courseContent TEXT,
  authorId INT,
  FOREIGN KEY (authorId) REFERENCES users (userId) ON DELETE SET NULL
) ENGINE=InnoDB;

-- 3. THE QUIZ TABLE
CREATE TABLE IF NOT EXISTS quiz (
  quizId INT AUTO_INCREMENT PRIMARY KEY,
  courseId INT NOT NULL,
  userId INT NOT NULL,
  score INT NOT NULL DEFAULT 0,
  totalQuestions INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (courseId) REFERENCES courses (courseId) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES users (userId) ON DELETE CASCADE
) ENGINE=InnoDB;